
import { JobListing } from "@/types";

// Job Listings Data
export const mockJobListings: JobListing[] = [
  {
    id: "job-1",
    employer_id: "emp-1",
    title: "Senior Frontend Developer",
    description: "We are looking for an experienced Frontend Developer to join our team. You will be responsible for building user interfaces for our web applications.",
    location: "San Francisco, CA",
    job_type: "full_time",
    salary_min: 120000,
    salary_max: 160000,
    salary_currency: "USD",
    requirements: [
      "5+ years of experience with React",
      "Strong knowledge of JavaScript/TypeScript",
      "Experience with modern frontend frameworks",
      "Understanding of responsive design principles",
    ],
    responsibilities: [
      "Develop user interfaces using React and TypeScript",
      "Collaborate with backend developers to integrate APIs",
      "Optimize applications for maximum performance",
      "Implement responsive design principles",
    ],
    is_active: true,
    created_at: "2023-01-15T08:00:00Z",
    updated_at: "2023-01-15T08:00:00Z",
    company_name: "TechCorp Inc.",
    company_logo_url: "https://placehold.co/40",
  },
  {
    id: "job-2",
    employer_id: "emp-2",
    title: "Backend Engineer",
    description: "Join our backend team to build scalable and efficient systems. You'll work on building APIs, optimizing database queries, and ensuring high performance.",
    location: "Seattle, WA",
    job_type: "full_time",
    salary_min: 130000,
    salary_max: 170000,
    salary_currency: "USD",
    requirements: [
      "3+ years experience with Node.js or Python",
      "Experience with SQL and NoSQL databases",
      "Knowledge of API design and development",
      "Understanding of microservices architecture",
    ],
    responsibilities: [
      "Design and implement RESTful APIs",
      "Optimize database queries for performance",
      "Implement authentication and authorization systems",
      "Write clean, maintainable, and well-tested code",
    ],
    is_active: true,
    created_at: "2023-02-20T10:30:00Z",
    updated_at: "2023-02-20T10:30:00Z",
    company_name: "DataFlow Systems",
    company_logo_url: "https://placehold.co/40",
  },
  {
    id: "job-3",
    employer_id: "emp-3",
    title: "UX/UI Designer",
    description: "We're seeking a talented UX/UI Designer to create beautiful, intuitive interfaces for our products. You'll work closely with product managers and developers.",
    location: "Remote",
    job_type: "full_time",
    salary_min: 90000,
    salary_max: 120000,
    salary_currency: "USD",
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency with design tools (Figma, Sketch)",
      "Portfolio showcasing design projects",
      "Understanding of user-centered design principles",
    ],
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with developers to implement designs",
      "Maintain and evolve our design system",
    ],
    is_active: true,
    created_at: "2023-03-05T09:15:00Z",
    updated_at: "2023-03-05T09:15:00Z",
    company_name: "Creative Solutions",
    company_logo_url: "https://placehold.co/40",
  },
  {
    id: "job-4",
    employer_id: "emp-1",
    title: "DevOps Engineer",
    description: "Looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll work on CI/CD pipelines, infrastructure as code, and monitoring systems.",
    location: "New York, NY",
    job_type: "full_time",
    salary_min: 140000,
    salary_max: 180000,
    salary_currency: "USD",
    requirements: [
      "3+ years of DevOps experience",
      "Strong knowledge of AWS or Azure",
      "Experience with Docker and Kubernetes",
      "Familiarity with Infrastructure as Code (Terraform, CloudFormation)",
    ],
    responsibilities: [
      "Implement and maintain CI/CD pipelines",
      "Manage cloud infrastructure using IaC",
      "Set up monitoring and alerting systems",
      "Automate deployment processes",
    ],
    is_active: true,
    created_at: "2023-04-10T14:20:00Z",
    updated_at: "2023-04-10T14:20:00Z",
    company_name: "TechCorp Inc.",
    company_logo_url: "https://placehold.co/40",
  },
  {
    id: "job-5",
    employer_id: "emp-2",
    title: "Product Manager",
    description: "Join our team as a Product Manager to lead product development from conception to launch. You'll work with cross-functional teams to deliver high-quality products.",
    location: "Boston, MA",
    job_type: "full_time",
    salary_min: 110000,
    salary_max: 150000,
    salary_currency: "USD",
    requirements: [
      "3+ years of product management experience",
      "Experience with Agile methodologies",
      "Strong analytical and problem-solving skills",
      "Excellent communication skills",
    ],
    responsibilities: [
      "Define product vision, strategy, and roadmap",
      "Work with engineering, design, and marketing teams",
      "Gather and analyze user feedback",
      "Prioritize features and improvements",
    ],
    is_active: true,
    created_at: "2023-05-15T11:45:00Z",
    updated_at: "2023-05-15T11:45:00Z",
    company_name: "DataFlow Systems",
    company_logo_url: "https://placehold.co/40",
  },
];
