// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhxqqtolltqebtnwmgsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoeHFxdG9sbHRxZWJ0bndtZ3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzYzNjEsImV4cCI6MjA2MDA1MjM2MX0.DeZIoQ7Df9cbz0nLNmT9Iu6uf7gD1R_SJ-jToRW_7iY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);